**4.1	Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:


1.	Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

In [ ]:
empty_array = np.empty((2, 2))

In [ ]:
print("Empty array is given below:\n",empty_array)


Empty array is given below:
 [[1.12412718e-315 0.00000000e+000]
 [6.94570963e-310 6.94570963e-310]]


2.	Initialize an all one array with size 4X2.

In [ ]:
ones_array = np.ones((4, 2))

In [ ]:
print("All one array is given below:\n",ones_array)

All one array is given below:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3.	Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
new_array = np.full((4, 4), 5)

In [ ]:
print("A new full array is given below:\n",new_array)

A new full array is given below:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


4.	Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
arr = np.array([[2, 3, 4], [5, 6, 7],[8,9,10]])

In [ ]:
zeros_arr = np.zeros_like(arr)

In [ ]:
print("A new array zeros is given below:\n",zeros_arr)

A new array zeros is given below:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


5.	Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_arr = np.ones_like(arr)

In [ ]:
print("A new array like ones is given below:\n",ones_arr)

A new array like ones is given below:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1, 2, 3, 4]

In [ ]:
converted_list = np.array(new_list)

In [ ]:
print("The converted list to array is given below:\n", converted_list)

The converted list to array is given below:
 [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:


1.	Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
range_array = np.arange(10, 50)

In [ ]:
print("A n array with values ranging from 10 to 49 is given below:\n", range_array)


A n array with values ranging from 10 to 49 is given below:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.	Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [ ]:
matrix = np.arange(9).reshape(3, 3)

In [ ]:
print("A 3x3 matrix ranging from 0 to 8 is given below:\n", matrix)


A 3x3 matrix ranging from 0 to 8 is given below:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3.	Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)

In [ ]:
print("An identity matrix of 3x3 is given below:\n", identity_matrix)

An identity matrix of 3x3 is given below:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.	Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [ ]:
random_array = np.random.random(30)

In [ ]:
print("A random array of size 30 is given below:\n", random_array)

A random array of size 30 is given below:
 [6.46400520e-01 5.22436753e-01 7.35840693e-02 6.47215219e-01
 2.72281573e-01 5.29164004e-01 5.49962375e-01 7.16310538e-01
 8.01028737e-01 4.39244165e-01 7.72819103e-01 4.48566515e-01
 9.41710479e-01 4.05976701e-01 9.75196926e-01 7.72524780e-01
 8.55355211e-01 7.07817043e-01 6.43609362e-01 4.69731023e-01
 7.33380019e-03 6.15398404e-01 4.19039836e-01 5.94252138e-01
 8.52611571e-01 2.60701948e-01 9.14012066e-04 3.48210288e-01
 3.68262779e-01 6.39094482e-01]


In [ ]:
print("Mean of given array is:", random_array.mean())

Mean of given array is: 0.5432251451234474


5.	Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_arr = np.random.random((10, 10))

In [ ]:
print("The minimum value is:", random_arr.min(), "\nThe maximum value is:", random_arr.max())

The minimum value is: 0.00018534512125811808 
The maximum value is: 0.9853141383973276


6.	Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_arr = np.zeros(10)

In [ ]:
zero_arr[4] = 1

In [ ]:
print("New array with replacing the 5th element with 1 is:\n", zero_arr)

New array with replacing the 5th element with 1 is:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.	Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
rev_arr = np.array([1, 2, 0, 0, 4, 0])

In [ ]:
rev = rev_arr[::-1]

In [ ]:
print("The reversed array is:\n", rev)

The reversed array is:
 [0 4 0 0 2 1]


8.	Create a 2d array with 1 on border and 0 inside.

In [ ]:
border = np.ones((4, 4))

In [ ]:
border[1:-1, 1:-1] = 0

In [ ]:
print("A 2d border array is:\n", border)

A 2d border array is:
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


9.	Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checker_board = np.zeros((8, 8), dtype=int)

In [ ]:
checker_board[1::2, ::2] = 1

In [ ]:
checker_board[::2, 1::2] = 1

In [ ]:
print("A checkerboard pattern 8x8 matrix is:\n", checker_board)

A checkerboard pattern 8x8 matrix is:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1.	Add the two array.


In [ ]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]]);
v=np.array([9,10])
w=np.array([11,12]);

In [ ]:
print(x)
print(y)
print(w)
print(v)
print(np.add(x,y))
print(np.add(w,v))

[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[11 12]
[ 9 10]
[[ 6  8]
 [10 13]]
[20 22]


2.	Subtract the two array.

In [ ]:
print(np.subtract(x,y))
print(np.subtract(w,v))

[[-4 -4]
 [-4 -3]]
[2 2]


3.	Multiply the array with any integers of your choice.

In [ ]:
print(x*3)
print(y*9)
print(v*7)
print(w*6)

[[ 3  6]
 [ 9 15]]
[[45 54]
 [63 72]]
[63 70]
[66 72]


4.	Find the square of each element of the array.

In [ ]:
x_sq = np.square(x)
y_sq = np.square(y)
v_sq = np.square(v)
w_sq = np.square(w)

In [ ]:
print("x square:\n", x_sq)
print("y square:\n", y_sq)
print("v square:\n", v_sq)
print("w square:\n", w_sq)

x square:
 [[ 1  4]
 [ 9 25]]
y square:
 [[25 36]
 [49 64]]
v square:
 [ 81 100]
w square:
 [121 144]


5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

219
[29 77]
[[19 22]
 [50 58]]


6.	Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
print(np.concatenate((x,y)))
print(np.vstack((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
print(np.concatenate((x,v)))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Problem - 4: Matrix Operations:**

 • For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1.	Prove A.A−1 = I.
2.	Prove AB ̸= BA.
3.	Prove (AB)T = BTAT.
•	Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
•	Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. A * A^-1 = I
A_inverse = np.linalg.inv(A)
print("A * A^-1:\n", np.dot(A, A_inverse))


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# 2. AB != BA
print("AB:\n", np.dot(A, B))
print("BA:\n", np.dot(B, A))


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [ ]:
# 3. (AB)^T = B^T * A^T
AB = np.dot(A, B)
lhs = AB.T
rhs = np.dot(B.T, A.T)
print("(AB)^T:\n", lhs)
print("B^T A^T:\n", rhs)

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print("Solution using inverse:\n", X)

Solution using inverse:
 [ 2.  1. -2.]


**4.2	Experiment: How Fast is Numpy?**
1. Element-wise Addition:

In [ ]:
import time

In [ ]:
N = 1000000
list1 = list(range(N))
list2 = list(range(N))

In [ ]:
start = time.time()
list_add = [list1[i] + list2[i] for i in range(N)]
end = time.time()
print("List addition time:", end - start)

List addition time: 0.1083381175994873


In [ ]:
np1 = np.arange(N)
np2 = np.arange(N)

In [ ]:
start = time.time()
np_add = np1 + np2
end = time.time()
print("NumPy addition time:", end - start)

NumPy addition time: 0.005915403366088867


2. Element-wise Multiplication

In [ ]:
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(N)]
end = time.time()
print("List multiplication time:", end - start)

List multiplication time: 0.11911225318908691


In [ ]:
start = time.time()
np_mul = np1 * np2
end = time.time()
print("NumPy multiplication time:", end - start)

NumPy multiplication time: 0.005833625793457031


3. Dot Product

In [ ]:
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(N))
end = time.time()
print("List dot product time is given below:", end - start)

List dot product time is given below: 0.12048649787902832


In [ ]:
start = time.time()
dot_np = np.dot(np1, np2)
end = time.time()
print("NumPy dot product time is given below:", end - start)

NumPy dot product time is given below: 0.0023603439331054688


4. Matrix Multiplication

In [ ]:
A = [[i for i in range(1000)] for _ in range(1000)]
B = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()
result_matrix = [[sum(a*b for a, b in zip(row, col))
                  for col in zip(*B)]
                  for row in A]
end = time.time()
print("List of matrix multiplication time is:", end - start)

List of matrix multiplication time is: 181.84453344345093


In [ ]:
matrix_1 = np.random.rand(1000, 1000)
matrix_2 = np.random.rand(1000, 1000)

start = time.time()
result_np = np.dot(matrix_1, matrix_2)
end = time.time()

print("NumPy matrix multiplication time is given below:", end - start)

NumPy matrix multiplication time is given below: 0.06770706176757812
